<?php

namespace MLB\DagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DagNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DagNodeRepository extends EntityRepository
{
}
