-- MySQL Script generated by MySQL Workbench
-- ven 21 ago 2015 18:31:14 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `dag_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dag_node` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 141
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dag_edge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dag_edge` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `incoming_edge_id` INT(11) NULL DEFAULT NULL,
  `direct_edge_id` INT(11) NULL DEFAULT NULL,
  `outgoing_edge_id` INT(11) NULL DEFAULT NULL,
  `start_node_id` INT(11) NULL DEFAULT NULL,
  `end_node_id` INT(11) NULL DEFAULT NULL,
  `hops` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_E7B25DFB6CBC52DC` (`incoming_edge_id` ASC),
  INDEX `IDX_E7B25DFBCBC6DED2` (`direct_edge_id` ASC),
  INDEX `IDX_E7B25DFB10FCD9D7` (`outgoing_edge_id` ASC),
  INDEX `IDX_E7B25DFBB6C8C304` (`start_node_id` ASC),
  INDEX `IDX_E7B25DFBD3C2CE3E` (`end_node_id` ASC),
  CONSTRAINT `FK_E7B25DFB10FCD9D7`
    FOREIGN KEY (`outgoing_edge_id`)
    REFERENCES `dag_edge` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_E7B25DFB6CBC52DC`
    FOREIGN KEY (`incoming_edge_id`)
    REFERENCES `dag_edge` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_E7B25DFBB6C8C304`
    FOREIGN KEY (`start_node_id`)
    REFERENCES `dag_node` (`id`),
  CONSTRAINT `FK_E7B25DFBCBC6DED2`
    FOREIGN KEY (`direct_edge_id`)
    REFERENCES `dag_edge` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_E7B25DFBD3C2CE3E`
    FOREIGN KEY (`end_node_id`)
    REFERENCES `dag_node` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 511
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
